server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/authenticationservice , classpath:config/filehandlerservice , classpath:config/fileconsumerservice , classpath:config/cloud-gateway
        encrypt:
          enabled: false
  profiles:
    active: native

