eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authenticationservice
          uri: lb://authenticationservice
          predicates:
            - Path=/auth/**
        - id: filehandlerservice
          uri: lb://filehandlerservice
          predicates:
            - Path=/fileupload/**
        - id: common-server
          uri: lb://common-server
          predicates:
            - Path=/common/**
server:
  port: 7171

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
