spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eyescloud?serverTimezone=Asia/Shanghai
    username: saber
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    admin:
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
      enabled: false
server:
  port: 8989
  servlet:
    context-path: /auth

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

