spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eyescloud?serverTimezone=Asia/Shanghai
    username: saber
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: saber
    password: saber
    virtual-host: /itcast
file:
  uploadFolder: file:D:\\c\\upload\\
  zipsoftPath: C:\\Program Files\\Bandizip\\bz.exe
  pythonFilePath: D:\\Python-WorkSpace\\10.26Main-副本\\main.py
  resultPath: D:\\c\\upload\\result\\
  zipPath: D:\\c\\upload\\zip\\
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8809
